Exit code: 1
---
Stdout:
======================= Schemathesis test session starts =======================
Schema location: http://127.0.0.1/schema.yaml
Base URL: http://127.0.0.1/api
Specification version: Open API 3.0.2
Random seed: 42
Workers: 1
Collected API operations: 4
Collected API links: 3
API probing: SUCCESS

GET /api/failure F                                                        [ 25%]
POST /api/users/ .                                                        [ 50%]
GET /api/users/{user_id} .                                                [ 75%]
PATCH /api/users/{user_id} .                                              [100%]

Stateful tests

...

=================================== FAILURES ===================================
_______________________________ GET /api/failure _______________________________
1. Test Case ID: <PLACEHOLDER>

- Server error

[500] Internal Server Error:

    `500: Internal Server Error`

Reproduce with: 

    <PLACEHOLDER>

________________________________ Stateful tests ________________________________
1. Test Case ID: <PLACEHOLDER>

- Server error

[500] Internal Server Error:

    `500 Internal Server Error

    Server got itself in trouble`

Reproduce with: 

    <PLACEHOLDER>

=================================== SUMMARY ====================================

Links                                                 2xx    4xx    5xx    Total

POST /api/users/
└── 201
    ├── GET /api/users/{user_id}
    └── PATCH /api/users/{user_id}

GET /api/users/{user_id}
└── 200
    └── PATCH /api/users/{user_id}

Performed checks:
    not_a_server_error                    N / N passed          FAILED 
    use_after_free                        N / N passed          PASSED 

Note: Use the 'X-Schemathesis-TestCaseId' header to correlate test case ids from failure messages with server logs for debugging.

Note: To replicate these test failures, rerun with `--hypothesis-seed=42`

========================= 2 failed in 1.00s ====================================
